export interface Country {
  code: string; // ISO 3166-1 alpha-2
  name: string;
}

function flag(code: string): string {
  return [...code.toUpperCase()].map(c => String.fromCodePoint(0x1F1E6 - 65 + c.charCodeAt(0))).join('');
}

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan' },
  { code: 'AL', name: 'Albania' },
  { code: 'DZ', name: 'Algeria' },
  { code: 'AD', name: 'Andorra' },
  { code: 'AO', name: 'Angola' },
  { code: 'AG', name: 'Antigua and Barbuda' },
  { code: 'AR', name: 'Argentina' },
  { code: 'AM', name: 'Armenia' },
  { code: 'AU', name: 'Australia' },
  { code: 'AT', name: 'Austria' },
  { code: 'AZ', name: 'Azerbaijan' },
  { code: 'BS', name: 'Bahamas' },
  { code: 'BH', name: 'Bahrain' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'BB', name: 'Barbados' },
  { code: 'BY', name: 'Belarus' },
  { code: 'BE', name: 'Belgium' },
  { code: 'BZ', name: 'Belize' },
  { code: 'BJ', name: 'Benin' },
  { code: 'BT', name: 'Bhutan' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'BA', name: 'Bosnia and Herzegovina' },
  { code: 'BW', name: 'Botswana' },
  { code: 'BR', name: 'Brazil' },
  { code: 'BN', name: 'Brunei' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi' },
  { code: 'CV', name: 'Cabo Verde' },
  { code: 'KH', name: 'Cambodia' },
  { code: 'CM', name: 'Cameroon' },
  { code: 'CA', name: 'Canada' },
  { code: 'CF', name: 'Central African Republic' },
  { code: 'TD', name: 'Chad' },
  { code: 'CL', name: 'Chile' },
  { code: 'CN', name: 'China' },
  { code: 'CO', name: 'Colombia' },
  { code: 'KM', name: 'Comoros' },
  { code: 'CG', name: 'Congo' },
  { code: 'CD', name: 'Congo (DRC)' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'CI', name: "Côte d'Ivoire" },
  { code: 'HR', name: 'Croatia' },
  { code: 'CU', name: 'Cuba' },
  { code: 'CY', name: 'Cyprus' },
  { code: 'CZ', name: 'Czech Republic' },
  { code: 'DK', name: 'Denmark' },
  { code: 'DJ', name: 'Djibouti' },
  { code: 'DM', name: 'Dominica' },
  { code: 'DO', name: 'Dominican Republic' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'EG', name: 'Egypt' },
  { code: 'SV', name: 'El Salvador' },
  { code: 'GQ', name: 'Equatorial Guinea' },
  { code: 'ER', name: 'Eritrea' },
  { code: 'EE', name: 'Estonia' },
  { code: 'SZ', name: 'Eswatini' },
  { code: 'ET', name: 'Ethiopia' },
  { code: 'FJ', name: 'Fiji' },
  { code: 'FI', name: 'Finland' },
  { code: 'FR', name: 'France' },
  { code: 'GA', name: 'Gabon' },
  { code: 'GM', name: 'Gambia' },
  { code: 'GE', name: 'Georgia' },
  { code: 'DE', name: 'Germany' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GR', name: 'Greece' },
  { code: 'GD', name: 'Grenada' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'GN', name: 'Guinea' },
  { code: 'GW', name: 'Guinea-Bissau' },
  { code: 'GY', name: 'Guyana' },
  { code: 'HT', name: 'Haiti' },
  { code: 'HN', name: 'Honduras' },
  { code: 'HU', name: 'Hungary' },
  { code: 'IS', name: 'Iceland' },
  { code: 'IN', name: 'India' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'IR', name: 'Iran' },
  { code: 'IQ', name: 'Iraq' },
  { code: 'IE', name: 'Ireland' },
  { code: 'IL', name: 'Israel' },
  { code: 'IT', name: 'Italy' },
  { code: 'JM', name: 'Jamaica' },
  { code: 'JP', name: 'Japan' },
  { code: 'JO', name: 'Jordan' },
  { code: 'KZ', name: 'Kazakhstan' },
  { code: 'KE', name: 'Kenya' },
  { code: 'KI', name: 'Kiribati' },
  { code: 'KP', name: 'Korea (North)' },
  { code: 'KR', name: 'Korea (South)' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'KG', name: 'Kyrgyzstan' },
  { code: 'LA', name: 'Laos' },
  { code: 'LV', name: 'Latvia' },
  { code: 'LB', name: 'Lebanon' },
  { code: 'LS', name: 'Lesotho' },
  { code: 'LR', name: 'Liberia' },
  { code: 'LY', name: 'Libya' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LT', name: 'Lithuania' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MW', name: 'Malawi' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'MV', name: 'Maldives' },
  { code: 'ML', name: 'Mali' },
  { code: 'MT', name: 'Malta' },
  { code: 'MH', name: 'Marshall Islands' },
  { code: 'MR', name: 'Mauritania' },
  { code: 'MU', name: 'Mauritius' },
  { code: 'MX', name: 'Mexico' },
  { code: 'FM', name: 'Micronesia' },
  { code: 'MD', name: 'Moldova' },
  { code: 'MC', name: 'Monaco' },
  { code: 'MN', name: 'Mongolia' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'MA', name: 'Morocco' },
  { code: 'MZ', name: 'Mozambique' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'NA', name: 'Namibia' },
  { code: 'NR', name: 'Nauru' },
  { code: 'NP', name: 'Nepal' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'NI', name: 'Nicaragua' },
  { code: 'NE', name: 'Niger' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'MK', name: 'North Macedonia' },
  { code: 'NO', name: 'Norway' },
  { code: 'OM', name: 'Oman' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'PW', name: 'Palau' },
  { code: 'PA', name: 'Panama' },
  { code: 'PG', name: 'Papua New Guinea' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'PE', name: 'Peru' },
  { code: 'PH', name: 'Philippines' },
  { code: 'PL', name: 'Poland' },
  { code: 'PT', name: 'Portugal' },
  { code: 'QA', name: 'Qatar' },
  { code: 'RO', name: 'Romania' },
  { code: 'RU', name: 'Russia' },
  { code: 'RW', name: 'Rwanda' },
  { code: 'KN', name: 'Saint Kitts and Nevis' },
  { code: 'LC', name: 'Saint Lucia' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines' },
  { code: 'WS', name: 'Samoa' },
  { code: 'SM', name: 'San Marino' },
  { code: 'ST', name: 'São Tomé and Príncipe' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'SN', name: 'Senegal' },
  { code: 'RS', name: 'Serbia' },
  { code: 'SC', name: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone' },
  { code: 'SG', name: 'Singapore' },
  { code: 'SK', name: 'Slovakia' },
  { code: 'SI', name: 'Slovenia' },
  { code: 'SB', name: 'Solomon Islands' },
  { code: 'SO', name: 'Somalia' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'SS', name: 'South Sudan' },
  { code: 'ES', name: 'Spain' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'SD', name: 'Sudan' },
  { code: 'SR', name: 'Suriname' },
  { code: 'SE', name: 'Sweden' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'SY', name: 'Syria' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'TJ', name: 'Tajikistan' },
  { code: 'TZ', name: 'Tanzania' },
  { code: 'TH', name: 'Thailand' },
  { code: 'TL', name: 'Timor-Leste' },
  { code: 'TG', name: 'Togo' },
  { code: 'TO', name: 'Tonga' },
  { code: 'TT', name: 'Trinidad and Tobago' },
  { code: 'TN', name: 'Tunisia' },
  { code: 'TR', name: 'Turkey' },
  { code: 'TM', name: 'Turkmenistan' },
  { code: 'TV', name: 'Tuvalu' },
  { code: 'UG', name: 'Uganda' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'US', name: 'United States' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'UZ', name: 'Uzbekistan' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'YE', name: 'Yemen' },
  { code: 'ZM', name: 'Zambia' },
  { code: 'ZW', name: 'Zimbabwe' },
];

export function countryFlag(code: string): string {
  return flag(code);
}

export function countryLabel(code: string): string {
  const c = COUNTRIES.find(c => c.code === code);
  return c ? `${flag(c.code)} ${c.name}` : code;
}

// Dial code → ISO country code (longest/most-specific match wins at detection time)
export const DIAL_CODES: Record<string, string> = {
  '1':    'US', '7':    'RU', '20':   'EG', '27':   'ZA', '30':   'GR',
  '31':   'NL', '32':   'BE', '33':   'FR', '34':   'ES', '36':   'HU',
  '39':   'IT', '40':   'RO', '41':   'CH', '43':   'AT', '44':   'GB',
  '45':   'DK', '46':   'SE', '47':   'NO', '48':   'PL', '49':   'DE',
  '51':   'PE', '52':   'MX', '53':   'CU', '54':   'AR', '55':   'BR',
  '56':   'CL', '57':   'CO', '58':   'VE', '60':   'MY', '61':   'AU',
  '62':   'ID', '63':   'PH', '64':   'NZ', '65':   'SG', '66':   'TH',
  '81':   'JP', '82':   'KR', '84':   'VN', '86':   'CN', '90':   'TR',
  '91':   'IN', '92':   'PK', '93':   'AF', '94':   'LK', '95':   'MM',
  '98':   'IR', '212':  'MA', '213':  'DZ', '216':  'TN', '218':  'LY',
  '220':  'GM', '221':  'SN', '222':  'MR', '223':  'ML', '224':  'GN',
  '225':  'CI', '226':  'BF', '227':  'NE', '228':  'TG', '229':  'BJ',
  '230':  'MU', '231':  'LR', '232':  'SL', '233':  'GH', '234':  'NG',
  '235':  'TD', '236':  'CF', '237':  'CM', '238':  'CV', '239':  'ST',
  '240':  'GQ', '241':  'GA', '242':  'CG', '243':  'CD', '244':  'AO',
  '245':  'GW', '246':  'IO', '248':  'SC', '249':  'SD', '250':  'RW',
  '251':  'ET', '252':  'SO', '253':  'DJ', '254':  'KE', '255':  'TZ',
  '256':  'UG', '257':  'BI', '258':  'MZ', '260':  'ZM', '261':  'MG',
  '262':  'RE', '263':  'ZW', '264':  'NA', '265':  'MW', '266':  'LS',
  '267':  'BW', '268':  'SZ', '269':  'KM', '290':  'SH', '291':  'ER',
  '297':  'AW', '298':  'FO', '299':  'GL', '350':  'GI', '351':  'PT',
  '352':  'LU', '353':  'IE', '354':  'IS', '355':  'AL', '356':  'MT',
  '357':  'CY', '358':  'FI', '359':  'BG', '370':  'LT', '371':  'LV',
  '372':  'EE', '373':  'MD', '374':  'AM', '375':  'BY', '376':  'AD',
  '377':  'MC', '378':  'SM', '380':  'UA', '381':  'RS', '382':  'ME',
  '385':  'HR', '386':  'SI', '387':  'BA', '389':  'MK', '420':  'CZ',
  '421':  'SK', '423':  'LI', '500':  'FK', '501':  'BZ', '502':  'GT',
  '503':  'SV', '504':  'HN', '505':  'NI', '506':  'CR', '507':  'PA',
  '508':  'PM', '509':  'HT', '590':  'GP', '591':  'BO', '592':  'GY',
  '593':  'EC', '594':  'GF', '595':  'PY', '596':  'MQ', '597':  'SR',
  '598':  'UY', '599':  'CW', '670':  'TL', '672':  'NF', '673':  'BN',
  '674':  'NR', '675':  'PG', '676':  'TO', '677':  'SB', '678':  'VU',
  '679':  'FJ', '680':  'PW', '681':  'WF', '682':  'CK', '683':  'NU',
  '685':  'WS', '686':  'KI', '687':  'NC', '688':  'TV', '689':  'PF',
  '690':  'TK', '691':  'FM', '692':  'MH', '850':  'KP', '852':  'HK',
  '853':  'MO', '855':  'KH', '856':  'LA', '880':  'BD', '886':  'TW',
  '960':  'MV', '961':  'LB', '962':  'JO', '963':  'SY', '964':  'IQ',
  '965':  'KW', '966':  'SA', '967':  'YE', '968':  'OM', '970':  'PS',
  '971':  'AE', '972':  'IL', '973':  'BH', '974':  'QA', '975':  'BT',
  '976':  'MN', '977':  'NP', '992':  'TJ', '993':  'TM', '994':  'AZ',
  '995':  'GE', '996':  'KG', '998':  'UZ',
};

/** Detect country from a phone number string that may start with +dialcode */
export function detectCountryFromPhone(value: string): string | null {
  const digits = value.replace(/^\+/, '');
  // Try 3-digit, then 2-digit, then 1-digit prefix
  for (const len of [3, 2, 1]) {
    const prefix = digits.slice(0, len);
    if (DIAL_CODES[prefix]) return DIAL_CODES[prefix];
  }
  return null;
}
