export { CheckoutClient } from './checkout.js';
export { createCheckout, createGatewayAdapter } from './extension.js';
export {
  createAuthorizeNetGateway,
  createBankTransferGateway,
  createCashOnDeliveryGateway,
  createCheckPaymentGateway,
  createPayPalGateway,
  createStripeExpressGateway,
  createStripeGateway,
  createWooPaymentsGateway,
} from './gateways.js';
export {
  createCheckoutTheme,
  createModernCheckoutTheme,
  createTailwindCheckoutTheme,
  createShadcnCheckoutTheme,
  MODERN_VARIABLES,
  TAILWIND_VARIABLES,
  SHADCN_VARIABLES,
} from './presets.js';
export { resolveTheme, getPresetVariables, MODERN_VARIABLES_DARK, TAILWIND_VARIABLES_DARK, SHADCN_VARIABLES_DARK } from './theme-engine.js';

export type {
  AuthorizeNetGatewayOptions,
  BankTransferGatewayOptions,
  CashOnDeliveryGatewayOptions,
  CheckPaymentGatewayOptions,
  CheckoutExpressBar,
  CheckoutExpressBarGateway,
  CheckoutOrderSummary,
  CheckoutShippingPackage,
  CheckoutShippingRate,
  CheckoutSummaryCoupon,
  CheckoutSummaryItem,
  CheckoutSummaryTotals,
  OfflineGatewayOptions,
  StripeExpressGatewayOptions,
  StripeInstance,
  StripeElementsInstance,
  CheckoutAddressInput,
  CheckoutExtension,
  CheckoutOptions,
  CheckoutFieldType,
  CheckoutFormDefinition,
  CheckoutFormField,
  CheckoutFormFieldOption,
  CheckoutFormSection,
  CheckoutGatewayActionContext,
  CheckoutGatewayAdapter,
  CheckoutGatewayPresentation,
  CheckoutGatewayRenderContext,
  CheckoutGatewayTokenizeContext,
  CheckoutPaymentMethod,
  CheckoutPaymentMethodsResponse,
  CheckoutProcessInput,
  CheckoutProcessResponse,
  CheckoutSDK,
  CheckoutSDKOptions,
  CheckoutState,
  CheckoutSubmitInput,
  CheckoutSubmitResult,
  CheckoutTheme,
  CheckoutThemeVariables,
  CheckoutThemeRules,
  CheckoutUpdateInput,
  CheckoutActionType,
  ConfirmPaymentActionData,
  MultibancoVoucherActionData,
  RedirectActionData,
  PaymentDataItem,
  PaymentResult,
  PaymentToken,
  ShippingMethodOption,
  PayPalGatewayOptions,
  StripeGatewayOptions,
  WooPaymentsGatewayOptions,
  // Checkout config
  CheckoutConfig,
  CheckoutFieldDefinition,
  CheckoutCountriesConfig,
  CheckoutShippingConfig,
  CheckoutAccountConfig,
  CheckoutStoreConfig,
  CheckoutValidationConfig,
  // Address autocomplete
  AddressProvider,
  AddressMatchedSubstring,
  AddressSuggestion,
  AddressSearchParams,
  AddressSearchResult,
  AddressDetailsParams,
  AddressDetails,
  // Order received / pay for order
  OrderAddress,
  OrderLineItem,
  OrderLineItemMeta,
  OrderTotalLine,
  AvailablePaymentMethod,
  OrderReceived,
  PayForOrderInput,
  PayForOrderResponse,
} from './types.js';

declare module '@cocartheadless/sdk' {
  interface CoCartExtensionRegistry {
    checkout: import('./types.js').CheckoutSDK;
  }
}
